name: photohunter Codecov

on:
  push

jobs:
  calculate-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Generate coverage report
        run: |
          mvn verify --file backend/pom.xml
      - uses: actions/upload-artifact@v2
        with:
          name: coverage-file
          path: backend/target/site/jacoco/jacoco.xml

  upload-coverage:
    runs-on: ubuntu-latest
    needs: calculate-coverage
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: coverage-file
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: jacoco.xml
#          directory: ./coverage/reports/
#          flags: unittests
          fail_ci_if_error: true
#          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true
