name: photohunter Codecov

on:
  push

jobs:
  codecov:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Generate coverage report
        run: |
          cd backend
          mvn test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./target/site/jacoco/jacoco.xml
          directory: ./coverage/reports/
          flags: unittests
          fail_ci_if_error: true
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true